### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by girodat** [cxhernandez/msmexplorer-d3#13]
I have been trying to install msmexplorer-d3 and I run into the error 

  File "app.py", line 87
    print "if youre developing locally, you need to get the MONGOLAB_URI"
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "if youre developing locally, you need to get the MONGOLAB_URI")?

when trying to run python app.py

I am not familiar with MONGOLAB or with heroku and I feel like the problem is within these two dependencies. 

Any help would be appreciated. 

Cheers,
Dylan

**Comment by cxhernandez** [comment]
Well, this particular error is due to two things: 1) using Python 3 to run a Python 2.7 app (see [conda-requirements.txt](https://github.com/msmexplorer/msmexplorer-d3/blob/master/conda-requirements.txt) for a full list of dependencies) and 2) it seems that [`MONGOLAB_URI` has be changed to `MONGODB_URI`](https://stackoverflow.com/a/39782007). You can find more information about this in the [Heroku docs](https://devcenter.heroku.com/articles/mongolab#getting-your-connection-uri).

It seems that the demo is also affected by these changes. In all honesty, I have not been maintaining this package since starting [msmbuilder/msmexplorer](https://github.com/msmbuilder/msmexplorer), so I'm not 100% sure how much work it might take to get this working on Heroku again.
